;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        mouse-yank-primary
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        evil-execute-in-normal-state
        keyboard-escape-quit
        ))
