;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		backward-sexp
		c-electric-colon
		c-electric-lt-gt
		c-electric-paren
		c-electric-semi&comma
		c-electric-slash
		dabbrev-expand
		downcase-region
		elpy-nav-backward-indent
		elpy-nav-forward-indent
		evil-append
		evil-append-line
		evil-backward-char
		evil-delete-backward-char-and-join
		evil-delete-char
		evil-end-of-line
		evil-forward-char
		evil-insert
		evil-next-line
		evil-normal-state
		evil-previous-line
		evil-search-forward
		evil-yank
		forward-sexp
		mouse-yank-primary
		org-beginning-of-line
		org-cycle
		org-force-self-insert
		org-self-insert-command
		smart-line-beginning
		toggle-identifier-naming-style
		whole-line-or-region-kill-region
		whole-line-or-region-yank
		yaml-electric-backspace
		yaml-electric-dash-and-dot
		))

(setq mc/cmds-to-run-once
      '(
		c-indent-line-or-region
		elpy-nav-indent-shift-left
		end-of-buffer
		evil-execute-in-normal-state
		evil-search-word-backward
		goto-line
		handle-switch-frame
		helm-buffers-list
		helm-find-files
		helm-mini
		keyboard-escape-quit
		mouse-set-region
		whole-line-or-region-kill-ring-save
		windmove-down-cycle
		windmove-up-cycle
		))
